{% set name = "pynini" %}
{% set version = "2.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://206.196.111.47/twiki/pub/GRM/Pynini/{{ name }}-{{ version }}.tar.gz
  sha256: fc06cc02adcbd4b14eb94ae9f2a0949d110612d2d4ee3a7ac5dc97b45fff8e33
  patches:
    - patches/0001-Add-Windows-build.patch  # [win]
    - patches/0002-Add-API-declarations.patch

build:
  number: 1

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - python                                  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - setuptools                              # [build_platform != target_platform]
    - cython >=3.0.6                          # [build_platform != target_platform]
    - m2-patch                                # [win]
  host:
    - cython >=3.0.6
    - openfst ==1.8.4
    - pip
    - python
    - setuptools
    - dlfcn-win32                             # [win]
  run:
    - graphviz
    - python
    - openfst ==1.8.4
    - ucrt                                    # [win]

test:
  imports:
    - pywrapfst
    - pynini

about:
  home: http://pynini.opengrm.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Finite-state grammar compilation
  description: |
    Pynini compiles grammars expressed as strings, regular expressions, and context-dependent rewrite rules into weighted finite-state transducers. It uses the OpenFst library and its Python extension to create, access and manipulate compiled grammars.
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/PyniniDocs

extra:
  recipe-maintainers:
    - kylebgorman
    - mmcauliffe
