{% set name = "pynini" %}
{% set version = "2.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.opengrm.org/twiki/pub/GRM/PyniniDownload/{{ name }}-{{ version }}.tar.gz
  sha256: f967b78a79f688ef8469f0da476799dbb005c817b4f0c164ee5f2ae99deed393
  patches:
    - patches/0001-Add-Windows-build.patch  # [win]
    - patches/0002-Add-API-declarations.patch

build:
  number: 6
  skip: true                                                                                              # [py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - cython                                  # [build_platform != target_platform]
    - m2-patch                                # [win]
  host:
    - cython >=0.29
    - openfst ==1.8.2
    - pip
    - python
    - dlfcn-win32                             # [win]
  run:
    - graphviz
    - python
    - openfst ==1.8.2
    - ucrt                                    # [win]

test:
  imports:
    - pywrapfst
    - pynini

about:
  home: http://pynini.opengrm.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Finite-state grammar compilation
  description: |
    Pynini compiles grammars expressed as strings, regular expressions, and context-dependent rewrite rules into weighted finite-state transducers. It uses the OpenFst library and its Python extension to create, access and manipulate compiled grammars.
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/PyniniDocs

extra:
  recipe-maintainers:
    - kylebgorman
    - mmcauliffe
