{% set name = "pynini" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.opengrm.org/twiki/pub/GRM/PyniniDownload/{{ name }}-{{ version }}.tar.gz
  sha256: b789f438cdf33a2c82ddd2c10f113dd1116b28d81d5ae516e3f79f5890a19ddd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win or py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29
    - openfst ==1.7.9
    - pip
    - python
  run:
    - graphviz
    - python
    - openfst ==1.7.9

test:
  imports:
    - pywrapfst
    - pynini

about:
  home: http://pynini.opengrm.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Finite-state grammar compilation
  description: |
    Pynini compiles grammars expressed as strings, regular expressions, and context-dependent rewrite rules into weighted finite-state transducers. It uses the OpenFst library and its Python extension to create, access and manipulate compiled grammars.
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/PyniniDocs

extra:
  recipe-maintainers:
    - kylebgorman
