{% set name = "pynini" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.opengrm.org/twiki/pub/GRM/PyniniDownload/{{ name }}-{{ version }}.tar.gz
  sha256: 74dd8ea124df1c9dec9300506560b6d6974384454e3a66ce5732fb5f82624f07

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win or py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29
    - openfst ==1.8.0
    - pip
    - python
  run:
    - graphviz
    - python
    - openfst ==1.8.0

test:
  imports:
    - pywrapfst
    - pynini

about:
  home: http://pynini.opengrm.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Finite-state grammar compilation
  description: |
    Pynini compiles grammars expressed as strings, regular expressions, and context-dependent rewrite rules into weighted finite-state transducers. It uses the OpenFst library and its Python extension to create, access and manipulate compiled grammars.
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/PyniniDocs

extra:
  recipe-maintainers:
    - kylebgorman
