{% set name = "pynini" %}
{% set version = "2.1.1" %}

package: 
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.opengrm.org/twiki/pub/GRM/PyniniDownload/{{ name }}-{{ version }}.tar.gz
  sha256: 5ba68459372a0ab2acbcb858ddde4604b7acec6edd68e5d926edb614913d13b0
  
build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win or py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29
    - openfst ==1.7.7
    - pip
    - python
  run:
    - graphviz
    - python
    - openfst ==1.7.7

test:
   imports:
      - pynini

about:
  home: http://pynini.opengrm.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Finite-state grammar compilation
  description: |
    Pynini compiles grammars expressed as strings, regular expressions, and context-dependent rewrite rules into weighted finite-state transducers. It uses the OpenFst library and its Python extension to create, access and manipulate compiled grammars.
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/PyniniDocs

extra:
  recipe-maintainers:
    - kylebgorman
